modLoader="javafml"
loaderVersion="[35,)"
license="Creative Commons"

[[mods]]
modId="genmod"
version="1.0"
displayName="Generation Mod"
credits=""
authors="bill8 and cliffhanger13"
description='''
A mod that will improve Minecraft's default terrain generation (among other things)
'''